# Generated by Django 4.2.21 on 2025-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
