# Generated by Django 4.2.21 on 2025-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0002_icon_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='s3_url',
            field=models.URLField(blank=True),
        ),
    ]
