services:
  - type: web
    name: bundled-icons
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn iconhub.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bundled-icons-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: iconhub.settings_prod

databases:
  - name: bundled-icons-db
    databaseName: bundled_icons
    user: bundled_icons_user 